# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-22 19:44
from __future__ import unicode_literals

import bili_api.models.ads
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('slug', models.SlugField(blank=True)),
                ('plan', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bili_api.models.ads.AdImage.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('az', models.CharField(blank=True, max_length=40, null=True)),
                ('en', models.CharField(blank=True, max_length=40, null=True)),
                ('ru', models.CharField(blank=True, max_length=40, null=True)),
                ('tr', models.CharField(blank=True, max_length=40, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bili_api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('az', models.CharField(blank=True, max_length=50, null=True)),
                ('en', models.CharField(blank=True, max_length=50, null=True)),
                ('ru', models.CharField(blank=True, max_length=50, null=True)),
                ('tr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bili_api.Ad')),
                ('no_bed_room', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bili_api.PaymentPeriod')),
            ],
            bases=('bili_api.ad',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicle', serialize=False, to='bili_api.Ad')),
                ('mileage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('year', models.IntegerField(blank=True, choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, null=True)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.CarBody')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.CarFuel')),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.CarMake')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.CarTransmission')),
            ],
            bases=('bili_api.ad',),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='bili_api.Person'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='bili_api.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='bili_api.Person'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='bili_api.Person'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bili_api.Ad'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='bili_api.Person'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bili_api.Ad'),
        ),
        migrations.AddField(
            model_name='adaddress',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='bili_api.Ad'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bili_api.Category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bili_api.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('person', 'ad')]),
        ),
    ]
