# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
