# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedaddon',
            name='add_on_type',
            field=models.ForeignKey(default='basic', on_delete=django.db.models.deletion.CASCADE, to='bili_api.AddOnType'),
            preserve_default=False,
        ),
    ]
