# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.CharField(default='56kfV-KuQZSeAWRU7bHD6g', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
