# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0002_auto_20170223_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarFuel',
            new_name='VehicleBody',
        ),
        migrations.RenameModel(
            old_name='CarTransmission',
            new_name='VehicleFuel',
        ),
        migrations.RenameModel(
            old_name='CarMake',
            new_name='VehicleMake',
        ),
        migrations.RenameModel(
            old_name='CarBody',
            new_name='VehicleModel',
        ),
        migrations.RenameModel(
            old_name='CarModel',
            new_name='VehicleTransmission',
        ),
    ]
