# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0002_auto_20170312_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='bili_api.Category'),
        ),
    ]
