# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0002_auto_20170303_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.CharField(default='edGkdhdgTkCwD00wT9n6qQ', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
