# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-03 00:12
from __future__ import unicode_literals

import bili_api.models.ads
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0002_auto_20170402_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_s300', models.ImageField(upload_to=bili_api.models.ads.thumbnails_directory_path)),
                ('ad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.Ad')),
            ],
        ),
        migrations.RemoveField(
            model_name='adthumbnail',
            name='ad',
        ),
        migrations.DeleteModel(
            name='AdThumbnail',
        ),
    ]
