# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-28 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0003_auto_20170328_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='Contact',
        ),
    ]
