# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0003_auto_20161113_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body',
            field=models.CharField(blank=True, choices=[('ANY', 'Any'), ('CAR_DERIVED_VAN', 'Car Derived Van'), ('CONVERTIBLE', 'Convertible'), ('COUPE', 'Coupe'), ('ESTATE', 'Estate'), ('HATCHBACK', 'Hatchback'), ('LIGHT4X4', 'Light 4x4'), ('MUSCLE', 'Muscle'), ('MINIBUS', 'Minibus'), ('MOTOR_CARAVAN', 'Motor Caravan'), ('MPV', 'MPV'), ('PANEL_VAN', 'Panel Van'), ('PICKUP', 'Pick Up'), ('SALOON', 'Saloon'), ('SPORTS', 'Sports'), ('WINDOW_VAN', 'Window Van'), ('OTHER', 'Other')], default='Any', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('ANY', 'Any'), ('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('GAS', 'Gas'), ('ELECTRIC', 'Electric'), ('GAS_BI_FUEL', 'Gas Bi Fuel'), ('HYBRID_ELECTRIC', 'Hybrid Electric'), ('PETROL/GAS', 'Petrol/Gas'), ('OTHER', 'Other')], default='Any', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank='True', choices=[('ANY', 'Any'), ('AC', 'AC'), ('ABARTH', 'Abarth'), ('AIXAM', 'Aixam'), ('ALFA_ROMEO', 'Alfa Romeo'), ('ASTON_MARTIN', 'Aston Martin'), ('AUDI', 'Audi'), ('AUSTIN', 'Austin'), ('BMW', 'BMW'), ('BENTLEY', 'Bentley'), ('BRISTOL', 'Bristol'), ('CADILLAC', 'Cadillac'), ('CATERHAM', 'Caterham'), ('CHEVROLET', 'Chevrolet'), ('CHERRY', 'Cherry'), ('CHRYSLER', 'Chrysler'), ('CITROEN', 'Citroen'), ('CORVETTE', 'Corvette'), ('DS', 'DS'), ('DACIA', 'Dacia'), ('DAEWOO', 'Daewoo'), ('DAIHATSU', 'Daihatsu'), ('DAIMLER', 'Daimler'), ('DODGE', 'Dodge'), ('FERRARI', 'Ferrari'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('HONDA', 'Honda'), ('HUMMER', 'Hummer'), ('HYUNDAI', 'Hyundai'), ('INFINITI', 'Infiniti'), ('INVICTA', 'Invicta'), ('ISUZU', 'Isuzu'), ('JAGUAR', 'Jaguar'), ('JEEP', 'Jeep'), ('KTM', 'KTM'), ('KIA', 'KIA'), ('LTI', 'LTI'), ('LADA', 'Lada'), ('LAMBORGHINI', 'Lamborghini'), ('LANCIA', 'Lancia'), ('LAND_ROWER', 'Land Rower'), ('LEXUS', 'Lexus'), ('LOTUS', 'Lotus'), ('MG', 'MG'), ('MG_MOTOR_UK', 'MG Motor UK'), ('MASERATI', 'MASERATI'), ('MAZDA', 'Mazda'), ('MCLAREN', 'Mclaren'), ('MERCEDES_BENZ', 'Mercedes Benz'), ('MICROCAR', 'Microcar'), ('MINI', 'Mini'), ('MITSUBISHI', 'Mitsubishi'), ('MORGAN', 'Morgan'), ('NISSAN', 'Nissan'), ('OPEL', 'Opel'), ('PERODUA', 'Perodua'), ('PEUGEOT', 'Peugeot'), ('PORCHE', 'Porche'), ('PROTON', 'Proton'), ('RELIANT', 'Reliant'), ('RENAULT', 'Renault'), ('ROLLS_ROYCE', 'Rolls-Royce'), ('ROVER', ' Rover'), ('SAAB', 'Saab'), ('SEAT', 'Seat'), ('SKODA', 'Skoda'), ('SMART', 'Smart'), ('SSANGYONG', 'Ssangyong'), ('SUBARU', 'Subaru'), ('SUZUKI', 'Suzuki'), ('TVR', 'TVR'), ('TALBOT', 'Talbot'), ('TATA', 'Tata'), ('TESLA', 'Tesla'), ('TOYOTA', 'Toyota'), ('VAUXHALL', 'Vauxhall'), ('VOLKSWAGEN', 'Volxwagen'), ('VOLVO', 'Volvo'), ('WESTFIELD', 'Westfield'), ('OTHER', 'Other')], default='Any', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('ANY', 'Any'), ('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('SEMI-AUTO', 'Semi Auto'), ('OTHER', 'Other')], default='Any', max_length=10, null=True),
        ),
    ]
