# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-26 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0003_auto_20170224_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='plan',
            new_name='add_on',
        ),
        migrations.AddField(
            model_name='ad',
            name='active_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='bili_api.Person'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.VehicleBody'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.VehicleFuel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bili_api.VehicleTransmission'),
        ),
    ]
