# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_auto_20170226_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('expiry_interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppliedAddOns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='addon add date')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add-on', to='bili_api.Ad')),
            ],
        ),
    ]
