# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_auto_20161113_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
