# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-09 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_auto_20170409_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchalert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
