# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_auto_20170324_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysetting',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
