# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0005_addontype_appliedaddons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedAddOns',
            new_name='AppliedAddOn',
        ),
        migrations.AddField(
            model_name='addontype',
            name='az',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='desc_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='desc_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addontype',
            name='tr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
