# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0005_auto_20170316_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lang_az', models.CharField(max_length=50)),
                ('lang_en', models.CharField(max_length=50)),
                ('lang_ru', models.CharField(max_length=50)),
                ('lang_tr', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='adaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adaddress',
            name='region',
        ),
        migrations.AlterField(
            model_name='adaddress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='bili_api.City'),
        ),
    ]
