# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-09 23:30
from __future__ import unicode_literals

import bili_api.custom_fields.lowercase_char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0005_auto_20170409_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchalert',
            name='search_term',
            field=bili_api.custom_fields.lowercase_char_field.LowerCaseCharField(max_length=150),
        ),
    ]
