# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0006_auto_20170324_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysetting',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to='bili_api.Profile'),
        ),
    ]
