# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0006_auto_20170226_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='add_on',
        ),
        migrations.AlterField(
            model_name='addontype',
            name='az',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='desc_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='desc_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='ru',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addontype',
            name='tr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appliedaddon',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_on', to='bili_api.Ad'),
        ),
    ]
