# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0006_auto_20170221_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='bili_api.Person'),
        ),
    ]
