# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-26 12:06
from __future__ import unicode_literals

import bili_api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0007_auto_20170325_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=bili_api.models.user.Profile.profile_pic_directory_path),
        ),
    ]
