# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-03 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0009_privacysetting_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='private',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='private',
        ),
    ]
