# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-04 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bili_api', '0010_auto_20170303_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notify', models.BooleanField(default=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
