# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0011_searchalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchalert',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
